on: 
  push:
    branches:
      - main

name: Build and Deploy
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Install and Build
      run: npm install & npm run docs

    - name: Deploy 🚀
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs
        publish_branch: github-pages
        keep_files: true
        user_name: 'Surjit Kumar Sahoo'
        user_email: 'surjitsahoo0@gmail.com'

    # - name: Deploy 🚀
    #   uses: JamesIves/github-pages-deploy-action@4.1.1
    #   with:
    #     branch: github-pages
    #     folder: docs
    #     git-config-name: Surjit Kumar Sahoo
    #     git-config-email: surjitsahoo0@gmail.com
