on: push
name: Run unit tests
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: setup Node
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Install
      run: npm install
    - name: Test
      run: npm test